spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:mysql://localhost:3309/identity-service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: qweasdzxcj01@gmail.com      # Gmail của bạn
    password: smozaaveymzqhajq         # App password (không dùng mật khẩu Gmail thường)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: TfoE5XGZnb7FLNJNdLupwTXgtLYmLtr5FxmgAp4kRCFH7bhEQJ1KIq40RC4LIWa6=
  access-token-expiration: 900000       # 15 phút
  refresh-token-expiration: 3600000 # 1h

